---
version: "3.3"

services: 
  app:
    build: .
    environment:
      - ENV=pro
    ports:
      - "8000:8000" 
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017" 
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root 
    volumes:
      - fair-money:/data/db

volumes:
  fair-money: